server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarymanagementdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: development
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload-directory: library-uploads
  folder-temp: ./library-temp/

logging:
  level:
    com.sinaukoding.library.management: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    defaultModelsExpandDepth: -1
    docExpansion: none
    tagsSorter: alpha
    operationsSorter: alpha